# Generated by Django 4.0.8 on 2022-12-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Points'), (2, 'Duration')])),
                ('value_points', models.IntegerField(null=True)),
                ('value_duration', models.DurationField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 1), ('value_duration__isnull', True), ('value_points__isnull', False)), models.Q(('type', 2), ('value_duration__isnull', False), ('value_points__isnull', True)), _connector='OR'), name='companies_score_value_matches_type'),
        ),
    ]
