# Generated by Django 4.0.8 on 2022-12-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_score_score_companies_score_value_matches_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
