# Generated by Django 4.0.8 on 2022-12-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_finals_finals_s_value_matches_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
