# Generated by Django 4.0.8 on 2022-12-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_company_company_wwww_value_matches_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='CTest',
        ),
        migrations.RemoveField(
            model_name='finals',
            name='user',
        ),
        migrations.RemoveField(
            model_name='finaltest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.RemoveConstraint(
            model_name='company',
            name='wwww_value_matches_type',
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 1), ('value_duration__isnull', True), ('value_points__isnull', False)), models.Q(('type', 2), ('value_duration__isnull', False), ('value_points__isnull', True)), _connector='OR'), name='companies_company_value_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(check=models.Q(('type__in', [1, 2])), name='companies_company_CompanyType_valid'),
        ),
        migrations.DeleteModel(
            name='FinalS',
        ),
        migrations.DeleteModel(
            name='FinalTest',
        ),
    ]
