# Generated by Django 4.0.8 on 2022-12-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_remove_company_companies_company_value_matches_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.IntegerField(choices=[(1, 'Points'), (2, 'Duration')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='value_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='value_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 1), ('value_duration__isnull', True), ('value_points__isnull', False)), models.Q(('type', 2), ('value_duration__isnull', False), ('value_points__isnull', True)), _connector='OR'), name='companies_company_value_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(check=models.Q(('type__in', [1, 2])), name='companies_company_CompanyType_valid'),
        ),
    ]
