# Generated by Django 4.0.8 on 2022-12-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_remove_company_companies_company_value_matches_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.IntegerField(choices=[(1, 'Points'), (2, 'Duration')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='value_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='value_points',
            field=models.IntegerField(null=True),
        ),
    ]
