# Generated by Django 4.0.8 on 2022-12-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_company_type_company_value_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='value_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='value_points',
            field=models.IntegerField(blank=True, null=True),
        ),
       
    ]
