# Generated by Django 4.0.8 on 2022-12-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_alter_company_value_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
