# Generated by Django 4.0.8 on 2022-12-11 21:32

from django.db import migrations, models
import django.db.models.expressions

def forwards_func(apps, schema_editor):
    Follow = apps.get_model("users", "Follow")
    db_alias = schema_editor.connection.alias
    Follow.objects.using(db_alias).filter(from_user=models.F("to_user")).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow_user_followers_follow_from_user_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=forwards_func,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('from_user', django.db.models.expressions.F('to_user')), _negated=True), name='users_follow_prevent_self_follow'),
        ),
    ]
